load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "4.4.2"
RULES_JVM_EXTERNAL_SHA = "735602f50813eb2ea93ca3f5e43b1959bd80b213b836a07a62a29d757670b77b"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/refs/tags/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

maven_install(
    artifacts = [
        "org.antlr:stringtemplate:4.0.2",

        # Fix for the following, due to a circular dep in antlr:
        #
        #   ERROR: /usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/7ac1967b990f2453d2320d3da05e6121/external/maven/BUILD:25:11: in jvm_import rule @maven//:org_antlr_stringtemplate: cycle in dependency graph:
        #       //:repro (6167a43bee81d7c4ceebdf8986e0027b728c609e76e2c99eb3032efb76afa9e5)
        #   .-> @maven//:org_antlr_stringtemplate (6167a43bee81d7c4ceebdf8986e0027b728c609e76e2c99eb3032efb76afa9e5)
        #   |   @maven//:org_antlr_antlr_runtime (6167a43bee81d7c4ceebdf8986e0027b728c609e76e2c99eb3032efb76afa9e5)
        #   `-- @maven//:org_antlr_stringtemplate (6167a43bee81d7c4ceebdf8986e0027b728c609e76e2c99eb3032efb76afa9e5)
        # References:
        # https://repo1.maven.org/maven2/org/antlr/stringtemplate/4.0.2/stringtemplate-4.0.2.pom
        # https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.3/antlr-runtime-3.3.pom

        # maven.artifact(
        #     "org.antlr",
        #     "antlr-runtime",
        #     "3.3",
        #     exclusions = [
        #         "org.antlr:stringtemplate",
        #     ],
        # ),
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)

